[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "firebase-admin>=6.9.0",
    "google-cloud-firestore>=2.21.0",
    "matplotlib>=3.10.3",
    "pandas>=2.3.0",
    "streamlit>=1.46.1",
]
